[workspace]
resolver = "3"
members = [
    "splat-overload",
    "splat-overload-test"
]
default-members = [
    "splat-overload",
    "splat-overload-test"
]

[workspace.package]
version = "0.0.0"
authors = [
    "teor <teor@riseup.net",
]
edition = "2024"
homepage = "https://rust-lang.github.io/rust-project-goals/2026/overloading-for-ffi.html"
keywords = [
    "overload",
    "C++",
    "interop",
]
license = "MIT OR APACHE-2.0"
readme = "README.md"
repository = "https://github.com/rustfoundation/overloading-macros"
[workspace.dependencies]
syn = { version = "2.0.119", features = ["full"] }
quote = "1.0.46"
proc-macro2 = "1.0.106"