[workspace]
resolver = "3"
members = [
    "splat-overload",
    "splat-overload-test"
]
default-members = [
    "splat-overload",
    "splat-overload-test"
]

[workspace.package]
version = "0.0.0"
authors = [
    "Ajay Singh <ajaykripa8736968359@gmail.com>",
    "teor <teor@riseup.net",
]
edition = "2024"
homepage = "https://rust-lang.github.io/rust-project-goals/2026/overloading-for-ffi.html"
keywords = [
    "overload",
    "C++",
    "interop",
]
license = "MIT OR APACHE-2.0"
readme = "README.md"
repository = "https://github.com/rustfoundation/overloading-macros"
# Requires nightly `#[rustc_splat]` which was renamed in nightly-2026-07-31 (rust-lang/rust#159817)
# We can't specify nightly here, because version suffixes aren't supported.
rust-version = "1.100"

[workspace.dependencies]
syn = { version = "2.0.119", features = ["full"] }
quote = "1.0.46"
proc-macro2 = "1.0.106"